GET http://localhost:8086/actuator
Accept: application/json

###
GET http://localhost:8085/customer?id=1
Accept: application/json

###
GET http://localhost:8085/customer?id=2
Accept: application/json

###
GET http://localhost:8085/customer?id=3
Accept: application/json

###
GET http://localhost:8085/customer?id=4
Accept: application/json

###
GET http://localhost:8085/customer?id=5
Accept: application/json

###
GET http://localhost:8085/customer?id=6
Accept: application/json

###
GET http://localhost:8085/customer?id=7
Accept: application/json

###
GET http://localhost:8085/customer?id=8
Accept: application/json

###
GET http://localhost:8085/customer?id=9
Accept: application/json

###
GET http://localhost:8085/customer?id=10
Accept: application/json

###
GET http://localhost:8085/customer?id=11
Accept: application/json

###
GET http://localhost:8085/customer?id=12
Accept: application/json

###
GET http://localhost:8085/customer?id=13
Accept: application/json

###
GET http://localhost:8085/customer?id=14
Accept: application/json

###
